spring:
  datasource:
    url: jdbc:h2:mem:bank-db
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
  application:
    name: loan-service
  config:
    import: optional:configserver:http://localhost:8083/
  profiles:
    active: default

server:
  port: 8082
