# Start with a base image containing Java runtime
FROM openjdk:17-slim AS build

# Information arround who maintaince the image
LABEL org.opencontainers.image.authors="chungtai0306@gmail.com"

# Add the application's jar to the container
COPY build/libs/account_service-0.0.1-SNAPSHOT.jar account_service-0.0.1-SNAPSHOT.jar 

#Execute the application
ENTRYPOINT [ "java","-jar","/account_service-0.0.1-SNAPSHOT.jar"]


