spring:
  datasource:
    url: jdbc:h2:mem:bank-db
    driverClassName: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: account-service
  config:
    import: optional:configserver:http://localhost:8083/
  profiles:
    active: prod
server:
  port: 8080
