account-service:
  msg: bd4e30bbf6627daeeefdb30aed32ccb751e7d47f442965c949bfbe6789263a3ef511741898409dc8fff9ee6b58955b37713899c36028135dd6d3416659342909
  build-version: 3

  mail-details:
    hostName: dev-account@gmail.com
    port: 8080
    from: dev-account@gmail.com
    subject: Your Account Details from Bank Dev Environment

  active-branches:
    - Chennai
    - Berlin
    - Indianapollis
