card-service:
  msg: Welcome to the Card Service Default application
  build-version: 3

  mail-details:
    hostName: prod-card@gmail.com
    port: 8080
    from: prod-card@gmail.com
    subject: Your Card Details from Bank Default Environment

  active-branches:
    - Mumbai
    - London
    - Washington
