card-service:
  msg: Welcome to the Card Service Dev application
  build-version: 3

  mail-details:
    hostName: dev-card@gmail.com
    port: 8080
    from: dev-card@gmail.com
    subject: Your Card Details from Bank Dev Environment

  active-branches:
    - Chennai
    - Berlin
    - Indianapollis
