loan-service:
  msg: Welcome to the Loan Service Dev application
  build-version: 3

  mail-details:
    hostName: prod-loan@gmail.com
    port: 8080
    from: prod-loan@gmail.com
    subject: Your Loan Details from Bank Dev Environment

  active-branches:
    - Chennai
    - Berlin
    - Indianapollis
